apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d5wgrcjaj-go-gitops
  description: This is GitOps manifest for d5wgrcjaj-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=d5wgrcjaj-go
    backstage.io/kubernetes-id: d5wgrcjaj-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: d5wgrcjaj-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:d5wgrcjaj-go
